import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1777988911426 implements MigrationInterface {
    name = 'InitSchema1777988911426'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP CONSTRAINT "reel_likes_reelId_fkey"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP CONSTRAINT "reel_likes_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "reels" DROP CONSTRAINT "reels_authorId_fkey"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "comments_authorId_fkey"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "comments_postId_fkey"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "comments_reelId_fkey"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "post_likes_postId_fkey"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "post_likes_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP CONSTRAINT "saved_posts_postId_fkey"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP CONSTRAINT "saved_posts_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "posts_authorId_fkey"`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP CONSTRAINT "story_views_storyId_fkey"`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP CONSTRAINT "story_views_viewerId_fkey"`);
        await queryRunner.query(`ALTER TABLE "stories" DROP CONSTRAINT "stories_authorId_fkey"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "follows_followerId_fkey"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "follows_followingId_fkey"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "conversation_participants_conversationId_fkey"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "conversation_participants_userId_fkey"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "messages_conversationId_fkey"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "messages_senderId_fkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_recipientId_fkey"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "reports_reporterId_fkey"`);
        await queryRunner.query(`DROP INDEX "public"."follows_followerId_followingId_key"`);
        await queryRunner.query(`DROP INDEX "public"."users_username_key"`);
        await queryRunner.query(`DROP INDEX "public"."users_email_key"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP CONSTRAINT "reel_likes_pkey"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD CONSTRAINT "reel_likes_pkey" PRIMARY KEY ("reelId")`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP CONSTRAINT "reel_likes_pkey"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD CONSTRAINT "reel_likes_pkey" PRIMARY KEY ("reelId", "userId")`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP CONSTRAINT "reel_likes_pkey"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD CONSTRAINT "PK_52f522090c41ae6c4d90edff020" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP COLUMN "reelId"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD "reelId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP CONSTRAINT "PK_52f522090c41ae6c4d90edff020"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD CONSTRAINT "PK_9390ba93a3d3894dfc086778567" PRIMARY KEY ("userId", "reelId")`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ALTER COLUMN "createdAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reels" DROP CONSTRAINT "reels_pkey"`);
        await queryRunner.query(`ALTER TABLE "reels" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "reels" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "reels" ADD CONSTRAINT "PK_e5ecdc818bad986f1eb0a5d7a2d" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "reels" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "reels" ADD "authorId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reels" DROP COLUMN "videoUrl"`);
        await queryRunner.query(`ALTER TABLE "reels" ADD "videoUrl" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reels" DROP COLUMN "audioTrack"`);
        await queryRunner.query(`ALTER TABLE "reels" ADD "audioTrack" character varying`);
        await queryRunner.query(`ALTER TABLE "reels" ALTER COLUMN "hashtags" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reels" ALTER COLUMN "hashtags" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "reels" ALTER COLUMN "createdAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reels" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reels" ALTER COLUMN "updatedAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reels" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "comments_pkey"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "authorId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "postId" uuid`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "reelId"`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "reelId" uuid`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "createdAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "post_likes_pkey"`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "post_likes_pkey" PRIMARY KEY ("postId")`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "post_likes_pkey"`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "post_likes_pkey" PRIMARY KEY ("postId", "userId")`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "post_likes_pkey"`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "PK_37d337ad54b1aa6b9a44415a498" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD "postId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "PK_37d337ad54b1aa6b9a44415a498"`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "PK_30ee85070afe5b92b5920957b1c" PRIMARY KEY ("userId", "postId")`);
        await queryRunner.query(`ALTER TABLE "post_likes" ALTER COLUMN "createdAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "post_likes" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP CONSTRAINT "saved_posts_pkey"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD CONSTRAINT "saved_posts_pkey" PRIMARY KEY ("postId")`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP CONSTRAINT "saved_posts_pkey"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD CONSTRAINT "saved_posts_pkey" PRIMARY KEY ("postId", "userId")`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP CONSTRAINT "saved_posts_pkey"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD CONSTRAINT "PK_2a6ac38aa1767f692d4f492639b" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD "postId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP CONSTRAINT "PK_2a6ac38aa1767f692d4f492639b"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD CONSTRAINT "PK_4d3790479b4ace0798f7d54c551" PRIMARY KEY ("userId", "postId")`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ALTER COLUMN "savedAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ALTER COLUMN "savedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "posts_pkey"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "authorId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "mediaUrls" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "mediaUrls" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TYPE "public"."PostType" RENAME TO "PostType_old"`);
        await queryRunner.query(`CREATE TYPE "public"."posts_type_enum" AS ENUM('IMAGE', 'CAROUSEL', 'VIDEO', 'TEXT')`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "type" TYPE "public"."posts_type_enum" USING "type"::"text"::"public"."posts_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."PostType_old"`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "hashtags" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "hashtags" SET DEFAULT '{}'`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "location" character varying`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "createdAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "updatedAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP CONSTRAINT "story_views_pkey"`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD CONSTRAINT "story_views_pkey" PRIMARY KEY ("viewerId")`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP COLUMN "storyId"`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD "storyId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP CONSTRAINT "story_views_pkey"`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD CONSTRAINT "story_views_pkey" PRIMARY KEY ("viewerId", "storyId")`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP CONSTRAINT "story_views_pkey"`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD CONSTRAINT "PK_59936d984aae9f264b569d35c9c" PRIMARY KEY ("storyId")`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP COLUMN "viewerId"`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD "viewerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP CONSTRAINT "PK_59936d984aae9f264b569d35c9c"`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD CONSTRAINT "PK_9b0ad717bf7b58e73d78c484e21" PRIMARY KEY ("storyId", "viewerId")`);
        await queryRunner.query(`ALTER TABLE "story_views" ALTER COLUMN "viewedAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "story_views" ALTER COLUMN "viewedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "stories" DROP CONSTRAINT "stories_pkey"`);
        await queryRunner.query(`ALTER TABLE "stories" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "stories" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "stories" ADD CONSTRAINT "PK_bb6f880b260ed96c452b32a39f0" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "stories" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "stories" ADD "authorId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stories" DROP COLUMN "mediaUrl"`);
        await queryRunner.query(`ALTER TABLE "stories" ADD "mediaUrl" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stories" DROP COLUMN "expiresAt"`);
        await queryRunner.query(`ALTER TABLE "stories" ADD "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stories" ALTER COLUMN "createdAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "stories" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "follows_pkey"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "PK_8988f607744e16ff79da3b8a627" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "followerId"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "followerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "followingId"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "followingId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."FollowStatus" RENAME TO "FollowStatus_old"`);
        await queryRunner.query(`CREATE TYPE "public"."follows_status_enum" AS ENUM('PENDING', 'ACCEPTED')`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "status" TYPE "public"."follows_status_enum" USING "status"::"text"::"public"."follows_status_enum"`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "status" SET DEFAULT 'ACCEPTED'`);
        await queryRunner.query(`DROP TYPE "public"."FollowStatus_old"`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "createdAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "conversation_participants_pkey"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_pkey" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP COLUMN "conversationId"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD "conversationId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "conversation_participants_pkey"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_pkey" PRIMARY KEY ("userId", "conversationId")`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "conversation_participants_pkey"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "PK_4453e20858b14ab765a09ad728c" PRIMARY KEY ("conversationId")`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "PK_4453e20858b14ab765a09ad728c"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "PK_e43efbfa3b850160b5b2c50e3ec" PRIMARY KEY ("conversationId", "userId")`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "conversations_pkey"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "conversations" ALTER COLUMN "createdAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "conversations" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "conversations" ALTER COLUMN "updatedAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "conversations" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "messages_pkey"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "PK_18325f38ae6de43878487eff986" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "conversationId"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "conversationId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "senderId"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "senderId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "mediaUrl"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "mediaUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "sentAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "sentAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "notifications_pkey"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "recipientId"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "recipientId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."NotificationType" RENAME TO "NotificationType_old"`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('LIKE', 'COMMENT', 'FOLLOW', 'FOLLOW_REQUEST', 'MENTION', 'MESSAGE')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "type" TYPE "public"."notifications_type_enum" USING "type"::"text"::"public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."NotificationType_old"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "referenceId"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "referenceId" character varying`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "actorId"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "actorId" character varying`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "createdAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "reports_pkey"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "reporterId"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "reporterId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "targetId"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "targetId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."ReportTarget" RENAME TO "ReportTarget_old"`);
        await queryRunner.query(`CREATE TYPE "public"."reports_targettype_enum" AS ENUM('POST', 'REEL', 'STORY', 'COMMENT', 'USER')`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "targetType" TYPE "public"."reports_targettype_enum" USING "targetType"::"text"::"public"."reports_targettype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ReportTarget_old"`);
        await queryRunner.query(`ALTER TYPE "public"."ReportStatus" RENAME TO "ReportStatus_old"`);
        await queryRunner.query(`CREATE TYPE "public"."reports_status_enum" AS ENUM('PENDING', 'REVIEWED', 'DISMISSED', 'ACTION_TAKEN')`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "status" TYPE "public"."reports_status_enum" USING "status"::"text"::"public"."reports_status_enum"`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."ReportStatus_old"`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "createdAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "updatedAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "users_pkey"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "username" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "fullName"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "fullName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatarUrl"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatarUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "websiteUrl"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "websiteUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "pronouns"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "pronouns" character varying`);
        await queryRunner.query(`ALTER TYPE "public"."Role" RENAME TO "Role_old"`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('USER', 'CREATOR', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."users_role_enum" USING "role"::"text"::"public"."users_role_enum"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'USER'`);
        await queryRunner.query(`DROP TYPE "public"."Role_old"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "fcmToken"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "fcmToken" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" TYPE TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "UQ_105079775692df1f8799ed0fac8" UNIQUE ("followerId", "followingId")`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD CONSTRAINT "FK_52f522090c41ae6c4d90edff020" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD CONSTRAINT "FK_786307fb6852744f867a7da8fbf" FOREIGN KEY ("reelId") REFERENCES "reels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reels" ADD CONSTRAINT "FK_4017f69e7ecc5351ae6759f952a" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_4548cc4a409b8651ec75f70e280" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_e44ddaaa6d058cb4092f83ad61f" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_6c545ee6ab36910ac7ea8fc29b6" FOREIGN KEY ("reelId") REFERENCES "reels"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "FK_6999d13aca25e33515210abaf16" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD CONSTRAINT "FK_2a6ac38aa1767f692d4f492639b" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD CONSTRAINT "FK_4704fa96cd2b591592a8cfaee56" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_c5a322ad12a7bf95460c958e80e" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD CONSTRAINT "FK_59936d984aae9f264b569d35c9c" FOREIGN KEY ("storyId") REFERENCES "stories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD CONSTRAINT "FK_684296961dffb07f81dd9063da0" FOREIGN KEY ("viewerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stories" ADD CONSTRAINT "FK_e36e259ea3b3799645774194033" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_fdb91868b03a2040db408a53331" FOREIGN KEY ("followerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "FK_ef463dd9a2ce0d673350e36e0fb" FOREIGN KEY ("followingId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "FK_4453e20858b14ab765a09ad728c" FOREIGN KEY ("conversationId") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "FK_18c4ba3b127461649e5f5039dbf" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_e5663ce0c730b2de83445e2fd19" FOREIGN KEY ("conversationId") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_db873ba9a123711a4bff527ccd5" FOREIGN KEY ("recipientId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_4353be8309ce86650def2f8572d" FOREIGN KEY ("reporterId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_4353be8309ce86650def2f8572d"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_db873ba9a123711a4bff527ccd5"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_2db9cf2b3ca111742793f6c37ce"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "FK_e5663ce0c730b2de83445e2fd19"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "FK_18c4ba3b127461649e5f5039dbf"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "FK_4453e20858b14ab765a09ad728c"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_ef463dd9a2ce0d673350e36e0fb"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "FK_fdb91868b03a2040db408a53331"`);
        await queryRunner.query(`ALTER TABLE "stories" DROP CONSTRAINT "FK_e36e259ea3b3799645774194033"`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP CONSTRAINT "FK_684296961dffb07f81dd9063da0"`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP CONSTRAINT "FK_59936d984aae9f264b569d35c9c"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_c5a322ad12a7bf95460c958e80e"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP CONSTRAINT "FK_4704fa96cd2b591592a8cfaee56"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP CONSTRAINT "FK_2a6ac38aa1767f692d4f492639b"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_6999d13aca25e33515210abaf16"`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "FK_37d337ad54b1aa6b9a44415a498"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_6c545ee6ab36910ac7ea8fc29b6"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_e44ddaaa6d058cb4092f83ad61f"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_4548cc4a409b8651ec75f70e280"`);
        await queryRunner.query(`ALTER TABLE "reels" DROP CONSTRAINT "FK_4017f69e7ecc5351ae6759f952a"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP CONSTRAINT "FK_786307fb6852744f867a7da8fbf"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP CONSTRAINT "FK_52f522090c41ae6c4d90edff020"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "UQ_105079775692df1f8799ed0fac8"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "fcmToken"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "fcmToken" text`);
        await queryRunner.query(`CREATE TYPE "public"."Role_old" AS ENUM('USER', 'CREATOR', 'ADMIN')`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" TYPE "public"."Role_old" USING "role"::"text"::"public"."Role_old"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'USER'`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."Role_old" RENAME TO "Role"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "pronouns"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "pronouns" text`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "websiteUrl"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "websiteUrl" text`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "avatarUrl"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "avatarUrl" text`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "fullName"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "fullName" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "email" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "username"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "username" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "users_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "updatedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`CREATE TYPE "public"."ReportStatus_old" AS ENUM('PENDING', 'REVIEWED', 'DISMISSED', 'ACTION_TAKEN')`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "status" TYPE "public"."ReportStatus_old" USING "status"::"text"::"public"."ReportStatus_old"`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."reports_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."ReportStatus_old" RENAME TO "ReportStatus"`);
        await queryRunner.query(`CREATE TYPE "public"."ReportTarget_old" AS ENUM('POST', 'REEL', 'STORY', 'COMMENT', 'USER')`);
        await queryRunner.query(`ALTER TABLE "reports" ALTER COLUMN "targetType" TYPE "public"."ReportTarget_old" USING "targetType"::"text"::"public"."ReportTarget_old"`);
        await queryRunner.query(`DROP TYPE "public"."reports_targettype_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."ReportTarget_old" RENAME TO "ReportTarget"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "targetId"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "targetId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "reporterId"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "reporterId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "PK_d9013193989303580053c0b5ef6"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "reports" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "reports_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "actorId"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "actorId" text`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "referenceId"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "referenceId" text`);
        await queryRunner.query(`CREATE TYPE "public"."NotificationType_old" AS ENUM('LIKE', 'COMMENT', 'FOLLOW', 'FOLLOW_REQUEST', 'MENTION', 'MESSAGE')`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "type" TYPE "public"."NotificationType_old" USING "type"::"text"::"public"."NotificationType_old"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."NotificationType_old" RENAME TO "NotificationType"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "recipientId"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "recipientId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "sentAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "messages" ALTER COLUMN "sentAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "mediaUrl"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "mediaUrl" text`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "senderId"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "senderId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "conversationId"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "conversationId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" DROP CONSTRAINT "PK_18325f38ae6de43878487eff986"`);
        await queryRunner.query(`ALTER TABLE "messages" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "messages" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "messages_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "conversations" ALTER COLUMN "updatedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "conversations" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "conversations" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "conversations" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP CONSTRAINT "PK_ee34f4f7ced4ec8681f26bf04ef"`);
        await queryRunner.query(`ALTER TABLE "conversations" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conversations" ADD CONSTRAINT "conversations_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "PK_e43efbfa3b850160b5b2c50e3ec"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "PK_4453e20858b14ab765a09ad728c" PRIMARY KEY ("conversationId")`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD "userId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "PK_4453e20858b14ab765a09ad728c"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_pkey" PRIMARY KEY ("userId", "conversationId")`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "conversation_participants_pkey"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_pkey" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP COLUMN "conversationId"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD "conversationId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" DROP CONSTRAINT "conversation_participants_pkey"`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_pkey" PRIMARY KEY ("conversationId", "userId")`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`CREATE TYPE "public"."FollowStatus_old" AS ENUM('PENDING', 'ACCEPTED')`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "status" TYPE "public"."FollowStatus_old" USING "status"::"text"::"public"."FollowStatus_old"`);
        await queryRunner.query(`ALTER TABLE "follows" ALTER COLUMN "status" SET DEFAULT 'ACCEPTED'`);
        await queryRunner.query(`DROP TYPE "public"."follows_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."FollowStatus_old" RENAME TO "FollowStatus"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "followingId"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "followingId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "followerId"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "followerId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "follows" DROP CONSTRAINT "PK_8988f607744e16ff79da3b8a627"`);
        await queryRunner.query(`ALTER TABLE "follows" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "follows" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "follows_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "stories" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "stories" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "stories" DROP COLUMN "expiresAt"`);
        await queryRunner.query(`ALTER TABLE "stories" ADD "expiresAt" TIMESTAMP(3) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stories" DROP COLUMN "mediaUrl"`);
        await queryRunner.query(`ALTER TABLE "stories" ADD "mediaUrl" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stories" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "stories" ADD "authorId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stories" DROP CONSTRAINT "PK_bb6f880b260ed96c452b32a39f0"`);
        await queryRunner.query(`ALTER TABLE "stories" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "stories" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "stories" ADD CONSTRAINT "stories_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "story_views" ALTER COLUMN "viewedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "story_views" ALTER COLUMN "viewedAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP CONSTRAINT "PK_9b0ad717bf7b58e73d78c484e21"`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD CONSTRAINT "PK_59936d984aae9f264b569d35c9c" PRIMARY KEY ("storyId")`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP COLUMN "viewerId"`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD "viewerId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP CONSTRAINT "PK_59936d984aae9f264b569d35c9c"`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD CONSTRAINT "story_views_pkey" PRIMARY KEY ("viewerId", "storyId")`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP CONSTRAINT "story_views_pkey"`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD CONSTRAINT "story_views_pkey" PRIMARY KEY ("viewerId")`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP COLUMN "storyId"`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD "storyId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "story_views" DROP CONSTRAINT "story_views_pkey"`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD CONSTRAINT "story_views_pkey" PRIMARY KEY ("storyId", "viewerId")`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "updatedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "location" text`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "hashtags" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "hashtags" DROP NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."PostType_old" AS ENUM('IMAGE', 'CAROUSEL', 'VIDEO', 'TEXT')`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "type" TYPE "public"."PostType_old" USING "type"::"text"::"public"."PostType_old"`);
        await queryRunner.query(`DROP TYPE "public"."posts_type_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."PostType_old" RENAME TO "PostType"`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "mediaUrls" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "posts" ALTER COLUMN "mediaUrls" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "authorId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "posts" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "posts_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ALTER COLUMN "savedAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ALTER COLUMN "savedAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP CONSTRAINT "PK_4d3790479b4ace0798f7d54c551"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD CONSTRAINT "PK_2a6ac38aa1767f692d4f492639b" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD "postId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP CONSTRAINT "PK_2a6ac38aa1767f692d4f492639b"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD CONSTRAINT "saved_posts_pkey" PRIMARY KEY ("postId", "userId")`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP CONSTRAINT "saved_posts_pkey"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD CONSTRAINT "saved_posts_pkey" PRIMARY KEY ("postId")`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD "userId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "saved_posts" DROP CONSTRAINT "saved_posts_pkey"`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD CONSTRAINT "saved_posts_pkey" PRIMARY KEY ("userId", "postId")`);
        await queryRunner.query(`ALTER TABLE "post_likes" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "post_likes" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "PK_30ee85070afe5b92b5920957b1c"`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "PK_37d337ad54b1aa6b9a44415a498" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD "postId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "PK_37d337ad54b1aa6b9a44415a498"`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "post_likes_pkey" PRIMARY KEY ("postId", "userId")`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "post_likes_pkey"`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "post_likes_pkey" PRIMARY KEY ("postId")`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD "userId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "post_likes" DROP CONSTRAINT "post_likes_pkey"`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "post_likes_pkey" PRIMARY KEY ("userId", "postId")`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "comments" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "reelId"`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "reelId" text`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "postId"`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "postId" text`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "authorId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "comments" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "comments_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "reels" ALTER COLUMN "updatedAt" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "reels" ALTER COLUMN "updatedAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "reels" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reels" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "reels" ALTER COLUMN "hashtags" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "reels" ALTER COLUMN "hashtags" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reels" DROP COLUMN "audioTrack"`);
        await queryRunner.query(`ALTER TABLE "reels" ADD "audioTrack" text`);
        await queryRunner.query(`ALTER TABLE "reels" DROP COLUMN "videoUrl"`);
        await queryRunner.query(`ALTER TABLE "reels" ADD "videoUrl" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reels" DROP COLUMN "authorId"`);
        await queryRunner.query(`ALTER TABLE "reels" ADD "authorId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reels" DROP CONSTRAINT "PK_e5ecdc818bad986f1eb0a5d7a2d"`);
        await queryRunner.query(`ALTER TABLE "reels" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "reels" ADD "id" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reels" ADD CONSTRAINT "reels_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ALTER COLUMN "createdAt" TYPE TIMESTAMP(3)`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP CONSTRAINT "PK_9390ba93a3d3894dfc086778567"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD CONSTRAINT "PK_52f522090c41ae6c4d90edff020" PRIMARY KEY ("userId")`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP COLUMN "reelId"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD "reelId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP CONSTRAINT "PK_52f522090c41ae6c4d90edff020"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD CONSTRAINT "reel_likes_pkey" PRIMARY KEY ("reelId", "userId")`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP CONSTRAINT "reel_likes_pkey"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD CONSTRAINT "reel_likes_pkey" PRIMARY KEY ("reelId")`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD "userId" text NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reel_likes" DROP CONSTRAINT "reel_likes_pkey"`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD CONSTRAINT "reel_likes_pkey" PRIMARY KEY ("userId", "reelId")`);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_email_key" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "users_username_key" ON "users" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "follows_followerId_followingId_key" ON "follows" ("followerId", "followingId") `);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "reports_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "notifications_recipientId_fkey" FOREIGN KEY ("recipientId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "messages_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "messages" ADD CONSTRAINT "messages_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "conversation_participants" ADD CONSTRAINT "conversation_participants_conversationId_fkey" FOREIGN KEY ("conversationId") REFERENCES "conversations"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "follows_followingId_fkey" FOREIGN KEY ("followingId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "follows" ADD CONSTRAINT "follows_followerId_fkey" FOREIGN KEY ("followerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "stories" ADD CONSTRAINT "stories_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD CONSTRAINT "story_views_viewerId_fkey" FOREIGN KEY ("viewerId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "story_views" ADD CONSTRAINT "story_views_storyId_fkey" FOREIGN KEY ("storyId") REFERENCES "stories"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "posts_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD CONSTRAINT "saved_posts_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "saved_posts" ADD CONSTRAINT "saved_posts_postId_fkey" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "post_likes_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "post_likes" ADD CONSTRAINT "post_likes_postId_fkey" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "comments_reelId_fkey" FOREIGN KEY ("reelId") REFERENCES "reels"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "comments_postId_fkey" FOREIGN KEY ("postId") REFERENCES "posts"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "comments_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reels" ADD CONSTRAINT "reels_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD CONSTRAINT "reel_likes_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "reel_likes" ADD CONSTRAINT "reel_likes_reelId_fkey" FOREIGN KEY ("reelId") REFERENCES "reels"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
